FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS servercoreruntime
ARG ARG_DOTNET_RUNTIME_VERSION
RUN powershell iwr 'https://dot.net/v1/dotnet-install.ps1' -OutFile './dotnet-install.ps1' && \
    powershell ./dotnet-install.ps1 -InstallDir 'C:/dotnet-runtime' -Runtime dotnet -Channel Current -Version %ARG_DOTNET_RUNTIME_VERSION%  && \
    setx /M PATH "%PATH%;C:\dotnet-runtime" && \
    setx /M DOTNET_CLI_TELEMETRY_OPTOUT "true" && \
    setx /M DOTNET_SKIP_FIRST_TIME_EXPERIENCE "true" && \
    setx /M DOTNET_RUNNING_IN_CONTAINER "true" && \
    setx /M DOTNET_RUNTIME_VERSION %ARG_DOTNET_RUNTIME_VERSION%
